const state = {
  _id: {},
  abstract: '',
  category: '',
  unit: '',
  note: '',
  comment: '',
  pic: '',
  completed: false,
  finishTime: '',
  insertTime: '',
  endDateGoal: '',
  remindTime: '',
  difficulty: 0,
  importanty: 0,
  priority: 0,
  repeated: false,
  repeatSpc: 0,
  subtask: [],
  finishedProgress: 0,
  totalProgress: 0,
  durationSum: 0,
  startProgress: 0,
  needRemind: false
}
